# Automatically generated by ProtoBuf.jl
module OSMPBF
  const _ProtoBuf_Top_ = @static isdefined(parentmodule(@__MODULE__), :_ProtoBuf_Top_) ? (parentmodule(@__MODULE__))._ProtoBuf_Top_ : parentmodule(@__MODULE__)
  include("fileformat_pb.jl")
  include("osmformat_pb.jl")
end
