# Modified from the file automatically generated by ProtoBuf.jl
# See https://github.com/pszufe/OpenStreetMapX.jl/pull/52/
module OSMPBF
  const _ProtoBuf_Top_ = @static isdefined(parentmodule(@__MODULE__), :_ProtoBuf_Top_) ? (parentmodule(@__MODULE__))._ProtoBuf_Top_ : parentmodule(@__MODULE__)

  using ProtoBuf
  abstract type SimpleProtoType <: ProtoType end
  set_defaults!(::SimpleProtoType) = nothing
  function ProtoBuf.clear(obj::SimpleProtoType)
      # FIXME how does it play with GC ?
      Base.unsafe_securezero!(pointer_from_objref(obj), sizeof(typeof(obj)))
      set_defaults!(obj)
      return
  end
  Base.hasproperty(obj::SimpleProtoType, field::Symbol) = isdefined(obj, field)
  Base.setproperty!(obj::SimpleProtoType, field::Symbol, value) = setfield!(obj, field, value)
  ProtoBuf.setdefaultproperties!(::SimpleProtoType, ::ProtoMeta) = nothing

  include("fileformat_pb.jl")
  include("osmformat_pb.jl")
end
