# Automatically generated by ProtoBuf.jl
module OSMPBF
  const _ProtoBuf_Top_ = @static isdefined(parentmodule(@__MODULE__), :_ProtoBuf_Top_) ? (parentmodule(@__MODULE__))._ProtoBuf_Top_ : parentmodule(@__MODULE__)

  using ProtoBuf
  abstract type SimpleProtoType <: ProtoType end
  set_defaults!(::SimpleProtoType) = nothing
  function ProtoBuf.clear(obj::SimpleProtoType)
      # FIXME how does it play with GC ?
      ccall(
            :memset,
            Ptr{Nothing},
            (Ptr{Nothing}, Cint, Csize_t),
            pointer_from_objref(obj),
            0,
            sizeof(typeof(obj)),
           )
      set_defaults!(obj)
      return
  end
  Base.hasproperty(obj::SimpleProtoType, field::Symbol) = isdefined(obj, field)
  Base.setproperty!(obj::SimpleProtoType, field::Symbol, value) = setfield!(obj, field, value)
  ProtoBuf.setdefaultproperties!(::SimpleProtoType, ::ProtoMeta) = nothing

  include("fileformat_pb.jl")
  include("osmformat_pb.jl")
end
